name: Waka Readme

on:
  schedule:
    # Runs daily at 12:00 UTC (adjust as needed)
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Cherrytree56567/hackatime-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: "True"         # Show timezone
          SHOW_EDITORS: "True"          # Show editors
          SHOW_LANGUAGE: "True"         # Show languages
          SHOW_PROJECTS: "True"         # Show projects
          # Hide everything else
          SHOW_OS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "False"
